export const siteConfig = {
  title: "Cylo",
  description:
    "A peer-to-peer marketplace for farmers and consumers to buy and sell agricultural products directly, eliminating the need for middlemen.",

  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    apple: "/favicon.svg",
  },

  ogTitle: "Cylo — Fair Trade. On-chain. For Every Farmer.",
  ogDescription:
    "Our platform connects farmers directly with buyers — it's the future for more food security, fair market prices and a flourishing ecosystem.",

  // Auto-generated by app/opengraph-image.tsx — no static file needed
  ogImage: "/opengraph-image",

  url: "https://cylo.vercel.app",

  tCard: "summary_large_image" as const,
  tTitle: "Cylo — Fair Trade. On-chain. For Every Farmer.",
  tDescription:
    "Our platform connects farmers directly with buyers — it's the future for more food security, fair market prices and a flourishing ecosystem.",
};
